# Generated by Django 5.2.15 on 2026-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('rent', 'Rent/Mortgage'), ('transport', 'Transportation'), ('dining', 'Dining Out'), ('health', 'Health/Medical'), ('education', 'Education'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
    ]
