# Generated by Django 5.2.15 on 2026-07-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_paychecktemplate_paychecktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paychecktemplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paychecktransaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='paychecktemplate',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
    ]
