# Generated by Django 5.2.15 on 2026-07-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_paychecktemplate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecktemplate',
            name='skipped_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
