# Generated by Django 5.2.15 on 2026-07-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_paychecktemplate_skipped_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecktemplate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
