# Generated by Django 5.2.15 on 2026-07-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychecktransaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
