# Generated by Django 5.2.15 on 2026-07-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_paychecktransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
