# Generated by Django 5.2.15 on 2026-07-25 02:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_categorybudget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybudget',
            options={'ordering': ['-effective_start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='effective_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to='transactions.category'),
        ),
        migrations.RemoveField(
            model_name='categorybudget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='categorybudget',
            name='year',
        ),
    ]
