# Generated by Django 5.2.15 on 2026-07-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_categorybudget_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('category', 'effective_start_date')},
        ),
    ]
