# Generated by Django 5.2.15 on 2026-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_categorybudget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransactiontemplate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
