# Generated by Django 5.2.15 on 2026-07-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_recurringtransactiontemplate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecktemplate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paychecktransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
